# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_wpinstance.mlc as __mlc
    mlc = __mlc
else:
    mlc = _utilities.lazy_import('pulumi_wpinstance.mlc')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "wpinstance",
  "mod": "mlc",
  "fqn": "pulumi_wpinstance.mlc",
  "classes": {
   "wpinstance:mlc:WpInstance": "WpInstance"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "wpinstance",
  "token": "pulumi:providers:wpinstance",
  "fqn": "pulumi_wpinstance",
  "class": "Provider"
 }
]
"""
)
